name: flutter_ravepay
description: Flutter integration for Flutterwave's Rave payment platform.
version: 0.1.1
author: Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
homepage: https://github.com/jogboms/flutter_ravepay

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ng.i.handikraft.flutterravepay
    pluginClass: FlutterRavepayPlugin
